### Production Environment Settings ###

# STS Role and target account
Sts.Role: arn:aws:iam::305261792510:role/admin

#VPCs
Config.Vpcs:
  Default:
    Cidr: 192.168.0.0/20
    Domain: dockerproductionaws.org